// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAaxE1epWzNMtpj3pNoE0v8zU0thlO1oM',
    appId: '1:61104540728:web:c4bdeb281773e1a492eacd',
    messagingSenderId: '61104540728',
    projectId: 'a-dollar-app',
    authDomain: 'a-dollar-app.firebaseapp.com',
    storageBucket: 'a-dollar-app.appspot.com',
    measurementId: 'G-QJXTG29565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEk8w9-TrtUiHijEftHa_JPj6jvYuxsEI',
    appId: '1:61104540728:android:58bb46a2ad7326ad92eacd',
    messagingSenderId: '61104540728',
    projectId: 'a-dollar-app',
    storageBucket: 'a-dollar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNLr4zJV1JSaslcbbMjuBZ2wyc-1IrOA',
    appId: '1:61104540728:ios:8f200cd84672154592eacd',
    messagingSenderId: '61104540728',
    projectId: 'a-dollar-app',
    storageBucket: 'a-dollar-app.appspot.com',
    iosClientId: '61104540728-qhsk6fr56g1vp0gg3kavct5hlba1tirt.apps.googleusercontent.com',
    iosBundleId: 'com.bigblunter.aDollarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlNLr4zJV1JSaslcbbMjuBZ2wyc-1IrOA',
    appId: '1:61104540728:ios:8f200cd84672154592eacd',
    messagingSenderId: '61104540728',
    projectId: 'a-dollar-app',
    storageBucket: 'a-dollar-app.appspot.com',
    iosClientId: '61104540728-qhsk6fr56g1vp0gg3kavct5hlba1tirt.apps.googleusercontent.com',
    iosBundleId: 'com.bigblunter.aDollarApp',
  );
}
